#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

ZDOTDIR=''

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/modules/k/k.sh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/modules/k/k.sh"
fi

if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/modules/ssh-connect/ssh-connect.sh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/modules/ssh-connect/ssh-connect.sh"
fi

if [[ -s "/usr/local/etc/profile.d/z.sh" ]]; then
  source "/usr/local/etc/profile.d/z.sh"
fi

if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/modules/history-search-multi-word/history-search-multi-word.plugin.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/modules/history-search-multi-word/history-search-multi-word.plugin.zsh"
fi

if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/modules/per-directory-history/per-directory-history.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/modules/per-directory-history/per-directory-history.zsh"
fi

# Customize to your needs...
alias nano='nano -c'

if [[ -s "${ZDOTDIR:-$HOME}/.zshrc.local" ]]; then
  source "${ZDOTDIR:-$HOME}/.zshrc.local"
fi
