#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

ZDOTDIR=''

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/modules/k/k.sh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/modules/k/k.sh"
fi

if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/modules/ssh-connect/ssh-connect.sh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/modules/ssh-connect/ssh-connect.sh"
fi

if [[ -s "/usr/local/etc/profile.d/z.sh" ]]; then
  source "/usr/local/etc/profile.d/z.sh"
fi

if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/modules/history-search-multi-word/history-search-multi-word.plugin.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/modules/history-search-multi-word/history-search-multi-word.plugin.zsh"
fi

if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/modules/per-directory-history/per-directory-history.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/modules/per-directory-history/per-directory-history.zsh"
fi

# Customize to your needs...
source /Users/alex/.zshrc-github-token
#export PATH=$(brew --prefix php)/bin:/Users/alex/Library/Android/sdk/platform-tools:/usr/local/bin:$PATH
export PATH=/Users/alex/Library/Android/sdk/platform-tools:/usr/local/bin:$PATH
export PATH=/usr/local/Cellar/ruby/2.4.1_1/bin:$PATH
export PATH=/usr/local/opt/coreutils/libexec/gnubin:$PATH

#alias vagrant='sudo vagrant'
alias meaweb='cd ~/Documents/Projects/Meaweb'

function homestead() {
    ( cd ~/Documents/Projects/Homestead && vagrant $* )
}

unalias mysql
ssh-add -K ~/.ssh/id_rsa &>/dev/null

function gitinit() {
    if [ $# -eq 0 ] || [ -z "$1" ] ; then
        echo "Remote origin argument is missing"
        return 1
    fi

    if [ -d .git ] ; then
        echo "Git already initialized"
        return 1
    fi

    git init && \
    git add . && \
    git commit -m 'Initial commit' && \
    git remote add origin $1 && \
    git push -u origin master
}
